# Generated by Django 5.1.2 on 2024-10-28 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='owner',
        ),
    ]
